### ISSUE TITLE
Add cargo-edit

### ISSUE THREAD

**Issue by kbknapp** [kbknapp/cargo-extras#1]
The binaries require an `extern crate cargo_edit` and I'm unsure of how to tell the binary where it's located from the `cargo-extras` manifest.

**Comment by killercup** [comment]
`extern crate cargo_edit` is just `src/lib.rs`. Does that help you in any way?

I've also thought about splitting the subcommand into separate crates (basically `src/bin/{add,rm,list}/main.rs` → `{add,rm,list}/src/main.rs`) to make them easier to `cargo install`.

**Comment by kbknapp** [comment]
No, I knew how it works internally, I mean the issue (I believe) is that the `[[bin]]` for `cargo-{list,add,rm}` gets compiled and it doesn't know where to find the `cargo_edit` crate because it's not being compiled with the normal directory structure.

So I guess, do you know a way to specify a lib for a particular `[[bin]]` table? Other than that, if you release the `cargo_edit` crate (lib) on crates.io instead of just inside the local crate, that would solve it too. Because then I can just list it as an external dependency.

As for splitting them into separate crates, I don't really think that's necessary. Since this repo is proof, installing multiple binaries from a single crate works perfectly fine and actually quite user-friendly/nice :smile:

**Comment by killercup** [comment]
> Other than that, if you release the cargo_edit crate (lib) on crates.io instead of just inside the local crate, that would solve it too. Because then I can just list it as an external dependency.

I'll do that, then! (Though maybe not today.)

**Comment by killercup** [comment]
Well, it took me a week, but I finally got around to publish cargo-edit on crates.io! https://crates.io/crates/cargo-edit

**Comment by kbknapp** [comment]
yay :+1: I'll update and test!

**Comment by killercup** [comment]
\o/
