### ISSUE TITLE
`cargo install cargo-extras` does not work on stable rust

### ISSUE THREAD

**Issue by colin-kiegel** [kbknapp/cargo-extras#17]
It looks like `cargo install cargo-extras` requires an unstable toolchain, due to clippy. `cargo install` itself is stable since rust 1.5.0. I think it would be better to exclude clippy from cargo-extras and to install it manually, so that `cargo install cargo-extras` can be used on a stable toolchain.

```
~/.cargo/registry/src/github.com-0a35038f75765ae4/clippy-0.0.30/src/lib.rs:1:1: 1:42 error: #[feature] may not be used on the stable release channel
~/.cargo/registry/src/github.com-0a35038f75765ae4/clippy-0.0.30/src/lib.rs:1 #![feature(plugin_registrar, box_syntax)]
```

**Comment by kbknapp** [comment]
This was fixed with #16 I just haven't released the new version to crates.io yet. You can install `cargo-extras` using a stable `rustc` from this git repo directly until I release the updated version to crates.io (should be soon :smile:)

```
$ cargo install cargo-extras --git https://github.com/kbknapp/cargo-extras.git
```

**Comment by kbknapp** [comment]
@colin-kiegel you should now be able to install `cargo-extras` using stable `rustc` from crates.io :wink:

```
$ cargo install cargo-extras
```

**Comment by colin-kiegel** [comment]
thx :-)
