### ISSUE TITLE
Consider changing cargo description

### ISSUE THREAD

**Issue by Ryman** [kbknapp/cargo-extras#26]
It might be worth adding a list of the installed commands to the cargo description metadata so as it appears when the user does `cargo search <related term>` rather than just saying "A collection of cargo subcommands" which means the user probably has to open a webbrowser and search for this repo to find the exact list. 

Perhaps even adding a link to the appropriate section of the readme would be enough.

**Comment by kbknapp** [comment]
Good idea, thanks! :+1:

**Comment by kbknapp** [comment]
Done, just waiting for `cargo-script` to build again and I'll update crates.io
